service: minebot

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:MINEBOT_TOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:*
          Resource: "*"

functions:
  webhook:
    handler: webhook.handler
    events:
      - http:
          path: /webhook
          method: post