service: minebot

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:MINEBOT_TOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: [
            # Instances
            "ec2:DescribeInstances",
            "ec2:StartInstances",
            "ec2:StopInstances",
            "ec2:TerminateInstances",
            "ec2:RebootInstances",
            "ec2:RunInstances",
            # Key Pairs
            "ec2:CreateKeyPair",
            "ec2:DeleteKeyPair",
            "ec2:DescribeKeyPairs",
            # Region
            "ec2:DescribeRegions",
            "ec2:DescribeAvailabilityZones",
            # Security Group
            "ec2:CreateSecurityGroup",
            "ec2:DeleteSecurityGroup",
            "ec2:DescribeSecurityGroups",
            "ec2:DescribeSecurityGroupRules",
            "ec2:ModifySecurityGroupRules",
            "ec2:AuthorizeSecurityGroupIngress",
          ]
          Resource: "*"

functions:
  webhook:
    handler: webhook.handler
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-offline